spring:
  application:
    name: bank-simulator
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-simulator
    username: dbuser
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-root.yml
server:
  port: 8080